# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ConvGRUCell": "00_layers.ipynb",
         "ConvGRU": "00_layers.ipynb",
         "DownSampler": "01_model.ipynb",
         "TemporalEncoder": "01_model.ipynb",
         "condition_time": "01_model.ipynb",
         "ConditionTime": "01_model.ipynb",
         "feat2image": "01_model.ipynb",
         "MetNet": "01_model.ipynb",
         "metnet_splitter": "01_model.ipynb"}

modules = ["layers.py",
           "model.py"]

doc_url = "https://tcapelle.github.io/metnet_pytorch/"

git_url = "https://github.com/tcapelle/metnet_pytorch/tree/master/"

def custom_doc_links(name): return None
